#!/bin/sh
echo "[test]\n" && make && time ./fillit ./map/valid_mapp/test && echo "___________________________\n"
echo "[test 10]\n" && make && time ./fillit ./map/valid_mapp/test10 && echo "___________________________\n"
echo "[test 11]\n" && make && time ./fillit ./map/valid_mapp/test11 && echo "___________________________\n"
echo "[test 12]\n" && make && time ./fillit ./map/valid_mapp/test12 && echo "___________________________\n"
echo "[test 13]\n" && make && time ./fillit ./map/valid_mapp/test13 && echo "___________________________\n"
echo "[test 14]\n" && make && time ./fillit ./map/valid_mapp/test14 && echo "___________________________\n"
echo "[test 15]\n" && make && time ./fillit ./map/valid_mapp/test15 && echo "___________________________\n"
echo "[test 26-0]\n" && make && time ./fillit ./map/valid_mapp/test26-0 && echo "___________________________\n"
echo "[test 26-2]\n" && make && time ./fillit ./map/valid_mapp/test26-2 && echo "___________________________\n"
echo "[test 26-3]\n" && make && time ./fillit ./map/valid_mapp/test26-3 && echo "___________________________\n"
echo "[test 26-4]\n" && make && time ./fillit ./map/valid_mapp/test26-4 && echo "___________________________\n"
echo "[test 26-5]\n" && make && time ./fillit ./map/valid_mapp/test26-5 && echo "___________________________\n"
echo "[test 26-6]\n" && make && time ./fillit ./map/valid_mapp/test26-6 && echo "___________________________\n"
echo "[test 26-7]\n" && make && time ./fillit ./map/valid_mapp/test26-7 && echo "___________________________\n"
echo "[test 26-8]\n" && make && time ./fillit ./map/valid_mapp/test26-8 && echo "___________________________\n"
echo "[test 26-9]\n" && make && time ./fillit ./map/valid_mapp/test26-9 && echo "___________________________\n"
echo "[test 26-1]\n" && make && time ./fillit ./map/valid_mapp/test26-1 && echo "___________________________\n"
echo "[testw]\n" && make && time ./fillit ./map/valid_mapp/testw && echo "___________________________\n"
echo "[testhard11]\n" && make && time ./fillit ./map/valid_mapp/testhard && echo "___________________________\n"
echo "[IMPOSSIBLE]\n" && make && time ./fillit ./map/valid_mapp/batard1.txt && echo "___________________________\n"
